name: 'Create sandbox in a veracode application'
description: 'creation of a sandbox in veracode'
inputs:
  application:  # id of input
    required: true
  sandbox:
    required: true
  type:
    required: true
outputs:
  random-number:
    value: 'Sandbox action has been done. '
runs:
  using: "composite"
  steps:
    - run: pip install -r secu-requirements.txt >> security.log
      shell: bash
    - run: python main.py ${{ inputs.application }} ${{ inputs.sandbox }} ${{ inputs.type }}
      shell: bash