name: 'Create sandbox in a veracode application'
description: 'creation of a sandbox in veracode'
inputs:
  application:  # id of input
    required: true
  sandbox:
    required: true
outputs:
  random-number:
    value: 'Sandbox named "toto" is created... '
runs:
  using: "composite"
  steps:
    - run: pip install -r secu-requirements.txt
      shell: bash
    - run: python create-application-version.py ${{ inputs.application }} ${{ inputs.sandbox }}
      shell: bash